name: 'Git Sync'
description: 'Git Sync is a tool that allows you to synchronize GitHub repositories with GitLab.'

branding:
  icon: git-merge
  color: orange

inputs:
  repo-url:
    description: 'Destination Repo URL'
    required: true
  repo-username:
    description: 'Destination Repo Username'
    required: true
  repo-token:
    description: 'Destination Repo User Token'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_REPO_URL: ${{ inputs.repo-url }}
        INPUT_REPO_USERNAME: ${{ inputs.repo-username }}
        INPUT_REPO_TOKEN: ${{ inputs.repo-token }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
