name: 'Git Sync'
description: 'Git Sync is a tool that allows you to synchronize GitHub repositories with GitLab.'

branding:
  icon: git-merge
  color: orange

inputs:
  repo-dest-url:
    description: 'GitLab Repo URL'
    required: true
  repo-dest-username:
    description: 'GitLab Repo Username'
    required: true
  repo-dest-token:
    description: 'GitLab Token'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        REPO_DEST_URL: ${{ inputs.repo-dest-url }}
        REPO_DEST_USERNAME: ${{ inputs.repo-dest-username }}
        REPO_DEST_TOKEN: ${{ inputs.repo-dest-token }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
