name: 'Git Sync'
description: 'Git Sync is a tool that allows you to synchronize GitHub repositories with GitLab.'

branding:
  icon: git-merge
  color: orange

inputs:
  gitlab-url:
    description: 'GitLab Repo URL'
    required: true
  gitlab-username:
    description: 'GitLab Repo Username'
    required: true
  gitlab-token:
    description: 'GitLab Token'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_GITLAB_URL: ${{ inputs.gitlab-url }}
        INPUT_GITLAB_USERNAME: ${{ inputs.gitlab-username }}
        INPUT_GITLAB_TOKEN: ${{ inputs.gitlab-token }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
