name: git-sync

on: 
  - push
  - delete

jobs:
  sync:
    runs-on: macos-latest
    name: Git Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: aramirol/git-sync@v1.0
      with:
        gitlab-url: https://github.com/aramirol/git-sync.git
        gitlab-username: aramirol
        gitlab-token: ${{ secrets.USER_TOKEN }}
