name: git-sync

on: 
  - push
  - delete

jobs:
  sync:
    runs-on: macos-latest
    name: Git Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: aramirol/git-sync@v0.1
      with:
        repo-url: https://github.com/aramirol/git-sync.git
        repo-username: aramirol
        repo-token: ${{ secrets.USER_TOKEN }}
